//Login Action
export const LOGIN_START="LOGIN_START";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const Login_FAILURE="LOGIN_FAILURE";
//Registration Action
export const REGISTRATION_START="REGISTRATION_START";
export const REGISTRATION_SUCCESS="REGISTRATION_SUCCESS";
export const REGISTRATION_FAILURE="REGISTRATION_FAILURE";
// Get Action
export const FETCH_START="FETCH_START";
export const FETCH_SUCCESS="FETCH_START";
export const FETCH_FAILURE="FETCH_FAILURE";
//Delete Action
export const DELETE_ITEM_START="DELETE_ITEM_START";
export const DELETE_ITEM_SUCCESS="DELETE_ITEM_SUCCESS";
export const DELETE_ITEM_FAILURE="DELETE_ITEM_FAILURE";